			<p class="navHeader">John Wadsworth</p>
			<ul id="navList">
				<li><a href="../about/residential.php"><b>Residential Message</b></a></li>
			    <li><a href="../about/commercial.php"><b>Commercial Message</b></a></li>
		    </ul>
			<p class="navHeader">Portfolio</p>
			<ul id="navList">
				<li><a href="../commercial/bay_state_savings.php"><b>Bay State Savings Bank</b><br />Worcester, MA</a></li>
			    <li><a href="../commercial/miles_funeral_home.php"><b>Miles Funeral Home</b><br />Holden, MA</a></li>
			    <li><a href="../commercial/zimmys_kitchen.php"><b>Zimmy's Kitchen</b><br />Leicester, MA</a></li>
		    </ul>
			<p class="navHeader"></p>
			<ul id="navList">
				<li><a href="../residential/boylston.php"><b>Private Residence</b><br />Boylston, MA</a></li>
				<li><a href="../residential/charlton.php"><b>Private Residence</b><br />Charlton, MA</a></li>
			    <li><a href="../residential/holden.php"><b>Private Residence One</b><br />Holden, MA</a></li>
			    <li><a href="../residential/holden2.php"><b>Private Residence Two</b><br />Holden, MA</a></li>
			    <li><a href="../residential/jefferson.php"><b>Private Residence</b><br />Jefferson, MA</a></li>
				<li><a href="../residential/lancaster.php"><b>Private Residence</b><br />Lancaster, MA</a></li>
				<li><a href="../residential/rutland.php"><b>Private Residence</b><br />Rutland, MA</a></li>
				<li><a href="../residential/sutton.php"><b>Private Residence</b><br />Sutton, MA</a></li>
			    <li><a href="../residential/worcester.php"><b>Private Residence One</b><br />Worcester, MA</a></li>
			    <li><a href="../residential/worcester2.php"><b>Private Residence Two</b><br />Worcester, MA</a></li>
			</ul>