			<p class="navHeader">John Wadsworth</p>
			<ul id="navList">
				<li><a href="../about/residential.php"><b>Residential Message</b></a></li>
			    <li><a href="../about/commercial.php"><b>Commercial Message</b></a></li>
		    </ul>
			<p class="navHeader">Commercial Portfolio</p>
			<ul id="navList">
				<li><a href="../commercial/country_bank.php"><b><u>Country Bank</u></b><br />Ware, MA</a></li>
				<li><a href="../commercial/age_center.php"><b><u>The Age Center</u></b><br />Whitcomb Hall Renovation<br />Worcester, MA</a></li>
				<li><a href="../commercial/bay_state_savings.php"><b><u>Bay State Savings Bank</u></b><br />Worcester, MA</a></li>
			    <li><a href="../commercial/mechanics_hall.php"><b><u>Mechanics Hall</u></b><br />Fuller Wing Addition<br />Worcester, MA</a></li>
			    <li><a href="../commercial/miles_funeral_home.php"><b><u>Miles Funeral Home</u></b><br />Holden, MA</a></li>
			    <li><a href="../commercial/tower_hill.php"><b><u>Tower Hill Botanical</u></b><br />Arbor: Secret Garden<br />Boylston, MA</a></li>
			    <li><a href="../commercial/zimmys_kitchen.php"><b><u>Zimmy's Kitchen</u></b><br />Leicester, MA</a></li>
		    </ul>
			<p class="navHeader">Residential Portfolio</p>
			
<ul id="navList">
  <li><a href="../residential/sturbridge.php"><b>Lake House</b>, Sturbridge, MA</a></li>
  <li><a href="../residential/barre.php"><b>Farmhouse</b>, Barre, MA</a></li>
  <li><a href="../residential/boylston.php"><b>Home</b>, Boylston, MA</a></li>
  <li><a href="../residential/charlton.php"><b>Home</b>, Charlton, MA</a></li>
  <li><a href="../residential/falmouth.php"><b>Home</b>, Falmouth, MA</a></li>
  <li><a href="../residential/holden.php"><b>Home One</b>, Holden, MA</a></li>
  <li><a href="../residential/holden2.php"><b>Home Two</b>, Holden, MA</a></li>
  <li><a href="../residential/holden3.php"><b>Home Three</b>, Holden, MA</a></li>
  <li><a href="../residential/jefferson.php"><b>Home</b>, Jefferson, MA</a></li>
  <li><a href="../residential/lancaster.php"><b>Home</b>, Lancaster, MA</a></li>
  <li><a href="../residential/lake_house.php"><b>Lake House</b>, MA</a></li>
  <li><a href="../residential/princeton.php"><b>House</b>, Princeton</a></li>
  <li><a href="../residential/sutton.php"><b>Home</b>, Sutton, MA</a></li>
  <li><a href="../residential/worcester.php"><b>Home One</b>, Worcester, MA</a></li>
  <li><a href="../residential/worcester2.php"><b>Home Two</b>, Worcester, MA</a></li>
  <li><a href="../residential/worcester3.php"><b>Home Three</b>, Worcester</a></li>
</ul>
